# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '9.0'
use_frameworks!

target 'RottenTomatoes' do
	pod 'AFNetworking'
	pod 'MBProgressHUD'
end

